language: cpp
sudo: required
dist: trusty

jobs:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages: 
            - g++-4.9
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages: 
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
        
    - os: osx
      osx_image: xcode7.3
        
    - os: osx
      osx_image: xcode10

  allow_failures:
    - os: osx
      osx_image: xcode7.3
        
    - os: osx
      osx_image: xcode10
before_install:
  - eval "${MATRIX_EVAL}"
  
before_script:
  - $CXX --version
  - cmake --version

script:
  - mkdir build && cd ./build
  - cmake ..
  - make
  - ./C3TL-test
  
branches:
  only:
  - master
  - release
  - dev
  - /^(?i:feature)-.*$/
  
notifications:
  email: false
