language: cpp
sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages: 
            - g++-4.9
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages: 
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        
    - os: osx
      osx_image: xcode7.3
        
    - os: osx
      osx_image: xcode8
        
    - os: osx
      osx_image: xcode9
        
    - os: osx
      osx_image: xcode10
        
before_install:
  - eval "${MATRIX_EVAL}"
  
before_script:
  - $CXX --version
  - cmake --version

script:
  - mkdir build && cd ./build
  - cmake ..
  - make
  - ./C3TL
  
branches:
  only:
  - master
  - release
  - dev
  - /^(?i:feature)-.*$/
  
notifications:
  email: false
